name: Feature request
description: Suggest an enhancement
labels: ["enhancement"]
body:
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: What problem are you trying to solve? What's the use case?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: How would you like this to work?
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
